// railway-rs/frontend/src/lib/components/AutoCompleteInput.svelte
<script>
  import { api } from '$lib/api.js'
  import { Badge } from '$lib/components/ui/badge/index.js'

  let {
    id = null,
    placeholder = 'Search…',
    kind = 'any',
    value = $bindable(''),
    onpick = () => {},
    inputClass = ''
  } = $props()

  let items = $state([])
  let open = $state(false)
  let active = $state(-1)
  let pos = $state(null)
  let controller = null
  let timer = null
  let rootEl = $state(null)
  let listEl = $state(null)
  const uid = `ac-${Math.random().toString(36).slice(2, 9)}`

  const filtered = $derived(
    items.filter((r) => {
      if (kind === 'any') return true
      return r.type === (kind === 'station' ? 'station' : 'train')
    })
  )

  function abort() {
    if (controller) {
      controller.abort()
      controller = null
    }
  }

  async function lookup(q) {
    abort()
    const c = new AbortController()
    controller = c
    const res = await api(`/rail-api/search/suggest?q=${encodeURIComponent(q)}`)
    if (c.signal.aborted) return
    controller = null
    if (res.ok && Array.isArray(res.data)) {
      items = res.data
      active = filtered.length > 0 ? 0 : -1
      open = true
    } else {
      items = []
      open = false
    }
  }

  function onInput() {
    clearTimeout(timer)
    const q = value.trim()
    if (!q) {
      abort()
      items = []
      open = false
      return
    }
    timer = setTimeout(() => lookup(q), 180)
  }

  function pick(item) {
    open = false
    abort()
    clearTimeout(timer)
    value =
      item.type === 'station'
        ? `${item.code}`
        : item.type === 'train'
          ? `${item.number}`
          : item.name
    onpick(item)
  }

  function move(delta) {
    if (!open || filtered.length === 0) return
    active = (active + delta + filtered.length) % filtered.length
  }

  function onKeydown(e) {
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      move(1)
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      move(-1)
    } else if (e.key === 'Enter') {
      if (open && filtered.length > 0) {
        e.preventDefault()
        pick(filtered[active] ?? filtered[0])
      }
    } else if (e.key === 'Escape') {
      open = false
    }
  }

  function place() {
    if (!rootEl || !open) return
    const r = rootEl.getBoundingClientRect()
    const gap = 4
    const margin = 8
    const spaceBelow = window.innerHeight - r.bottom - margin
    const spaceAbove = r.top - margin
    const flip = spaceBelow < 96 && spaceAbove > spaceBelow
    const avail = flip ? spaceAbove - gap : spaceBelow - gap
    pos = flip
      ? {
          left: r.left,
          width: r.width,
          bottom: window.innerHeight - r.top + gap,
          maxHeight: Math.max(120, Math.min(288, avail))
        }
      : {
          left: r.left,
          width: r.width,
          top: r.bottom + gap,
          maxHeight: Math.max(120, Math.min(288, avail))
        }
  }

  function onDocumentClick(e) {
    const t = e.target
    if (rootEl && !rootEl.contains(t) && !(listEl && listEl.contains(t))) open = false
  }

  function portal(node) {
    document.body.appendChild(node)
    return {
      destroy() {
        node.remove()
      }
    }
  }

  $effect(() => {
    document.addEventListener('click', onDocumentClick)
    return () => document.removeEventListener('click', onDocumentClick)
  })

  $effect(() => {
    if (!open) return
    place()
    window.addEventListener('resize', place)
    window.addEventListener('scroll', place, true)
    return () => {
      window.removeEventListener('resize', place)
      window.removeEventListener('scroll', place, true)
    }
  })

  $effect(() => {
    return () => {
      abort()
      clearTimeout(timer)
    }
  })
</script>

<div class="relative" bind:this={rootEl}>
  <input
    {id}
    bind:value
    oninput={onInput}
    onfocus={onInput}
    onkeydown={onKeydown}
    {placeholder}
    autocomplete="off"
    class={`flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs transition-colors placeholder:text-muted-foreground focus-visible:border-ring focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 ${inputClass}`}
    aria-autocomplete="list"
    aria-expanded={open}
    aria-controls={open && filtered.length > 0 ? `${uid}-list` : undefined}
    role="combobox"
  />
</div>

{#if open && filtered.length > 0 && pos}
  <div
    use:portal
    bind:this={listEl}
    id={`${uid}-list`}
    role="listbox"
    style={`left:${pos.left}px;width:${pos.width}px;max-height:${pos.maxHeight}px;${
      pos.top !== undefined ? `top:${pos.top}px` : `bottom:${pos.bottom}px`
    }`}
    class="fixed z-50 overflow-y-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md"
  >
    {#each filtered as r, i ((r.type ?? '') + (r.code ?? '') + (r.number ?? ''))}
      <button
        type="button"
        role="option"
        aria-selected={i === active}
        class={`flex w-full items-center justify-between gap-2 rounded-sm px-2 py-1.5 text-left text-sm ${
          i === active ? 'bg-accent text-accent-foreground' : ''
        }`}
        onmousedown={(e) => {
          e.preventDefault()
          pick(r)
        }}
        onmouseenter={() => (active = i)}
      >
        <span class="truncate">{r.name}</span>
        {#if r.code}<Badge variant="outline" class="shrink-0 font-mono">{r.code}</Badge>
        {:else if r.number}<Badge variant="outline" class="shrink-0 font-mono">{r.number}</Badge>{/if}
      </button>
    {/each}
  </div>
{/if}

// src/components/AutocompleteInput.tsx
import React, { useState, useEffect, useRef } from 'react';

interface Props {
  type: 'train' | 'station';
  value: string;
  onChange: (val: string) => void;
  placeholder: string;
  icon?: React.ReactNode;
  className?: string;
}

export default function AutocompleteInput({ type, value, onChange, placeholder, icon, className }: Props) {
  const [query, setQuery] = useState(value);
  const [results, setResults] = useState<any[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setQuery(value);
  }, [value]);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  useEffect(() => {
    if (!query || query === value && !isOpen) {
      setResults([]);
      return;
    }
    const timer = setTimeout(async () => {
      try {
        const endpoint = type === 'train' ? '/rail-api/search/trains' : '/rail-api/search/stations';
        const searchTerm = query.split(' - ')[0].trim();
        const res = await fetch(`${endpoint}?q=${encodeURIComponent(searchTerm)}`);
        const json = await res.json();
        setResults(json);
        if (json.length > 0) setIsOpen(true);
      } catch (err) {
        setResults([]);
      }
    }, 300);
    return () => clearTimeout(timer);
  }, [query, type, value, isOpen]);

  const handleSelect = (item: any) => {
    const val = type === 'train' ? `${item.number} - ${item.name}` : `${item.code} - ${item.name}`;
    setQuery(val);
    onChange(val);
    setIsOpen(false);
  };

  return (
    <div className={`relative flex-1 group ${className || ''}`} ref={wrapperRef}>
      {icon && (
        <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none z-10">
          {icon}
        </div>
      )}
      <input
        type="text"
        value={query}
        onChange={(e) => {
          const val = e.target.value.toUpperCase();
          setQuery(val);
          onChange(val);
          setIsOpen(true);
        }}
        onFocus={() => { if (results.length > 0) setIsOpen(true); }}
        placeholder={placeholder}
        className={`w-full bg-slate-100 text-slate-900 px-4 py-3 rounded-xl font-bold text-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${icon ? 'pl-12' : ''}`}
        required
      />
      
      {isOpen && results.length > 0 && (
        <div className="absolute top-full left-0 right-0 mt-2 bg-white rounded-xl shadow-xl border border-slate-200 overflow-hidden z-50 max-h-60 overflow-y-auto">
          {results.map((item, idx) => (
            <div
              key={idx}
              onClick={() => handleSelect(item)}
              className="p-3 border-b border-slate-100 hover:bg-slate-50 cursor-pointer flex justify-between items-center"
            >
              <div className="flex items-center gap-3">
                <span className="font-bold text-slate-900 bg-slate-100 px-2 py-1 rounded text-sm whitespace-nowrap">
                  {type === 'train' ? item.number : item.code}
                </span>
                <span className="text-slate-600 font-medium text-sm truncate max-w-[200px] md:max-w-xs">
                  {item.name}
                </span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
